-- Listings are now created via the wizard once an account exists,
-- since each listing requires a dress_id from the new dresses table
-- (Phase 1 of the dress-as-first-class-entity refactor). Seeding
-- listings without a real seller / wizard flow doesn't reflect how
-- the marketplace actually works, so this file is intentionally
-- empty post-migration.
--
-- Reference data (designers, occasions, fabrics, etc.) is seeded
-- inline in schema.sql; nothing else here is required for the app
-- to boot.
SELECT 1 WHERE FALSE;
